app:
  api:
    swagger:
      enable: true
  message: This is properties configuration for ${spring.application.name} from PRIMARY environment    
      
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
      
file:
  upload-dir: C:/Users/saura/Projects/ProjectFiles/smartPay/primary/Images/Uplaod
  
hibernate:
  cache:
    region:
      factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
    use_second_level_cache: true
    
jwt:
  header: Authorization
  key: jxgEQeXHuPq8VdbyYFNkANdudQ53YUn4
  
logging:
  file:
    name: C:/Users/saura/Projects/SmartPay_Logger/SmartPay/primary/SmartPay.log
  level:
    com:
      Smartpay: debug
    org:
      springframework:
        security:
          web:
            FilterChainProxy: debug
    root: info
    
server:
  error:
    include-stacktrace: never
  port: 6060
    
spring:
  application:
    name: SmartPay
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: SmartPay
    password: 12345
    platform: mysql
    url: jdbc:mysql://localhost:3306/smartPayLocal?serverTimezone=UTC
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
#  config:
#     import: optional:ConfigurationService:http://localhost:4040

  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 65324304311-tvh4snq709m3abctjfs83g1arlu06t83.apps.googleusercontent.com
            client-secret: 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
            
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 20KB
      max-file-size: 10MB
      max-request-size: 20MB
      
  cloud:
      config:
          enabled: false
      compatibility-verifier:
          enabled: false
  
  sleuth:
      propagation:
          type: w3c,b3
          
#  profiles:
#    active: dev     #dev ,test, uat, prod  #VM Arguments
                           #@  -Dspring.profiles.active=qa   
          
merchant:
    onboarding:
        inital:
            schedular:
                enable: true
        api:
          timer: 5000
          
management:
    security:
        enabled: false
    health:
        consul:
            enabled: false        
          
  
             
   
        